"""
Gradio demo app for the Pet Food Recall Risk Classification project.

This file will be deployed as a Hugging Face Space.

TODO (Phase 9):
  - Load the selected classifier and label binarizer from the Hub or local path
  - Wire up the predict() function from src/predict.py
  - Display predicted labels, confidence scores, and short explanations
  - Add the disclaimer notice to the UI
"""

import gradio as gr

DISCLAIMER = (
    "⚠️ This tool is for educational purposes only. "
    "Predictions are generated by a machine learning model and may be incorrect. "
    "Always consult official FDA recall notices and a qualified veterinarian "
    "for authoritative pet food safety information."
)

LABELS = [
    "PATHOGEN_CONTAMINATION",
    "MYCOTOXIN_OR_CHEMICAL_CONTAMINATION",
    "NUTRITIONAL_IMBALANCE_OR_TOXICITY",
    "FOREIGN_MATERIAL_CONTAMINATION",
    "LABELING_OR_UNDECLARED_INGREDIENT_ISSUE",
    "QUALITY_OR_PROCESS_CONTROL_ISSUE",
]


def classify(brand: str, product: str, reason: str) -> str:
    """Placeholder prediction function — model not trained yet."""
    # TODO: call the real predict() function once the model is available
    return "Model not trained yet. Please check back after Phase 9."


with gr.Blocks(title="Pet Food Recall Risk Classifier") as demo:
    gr.Markdown("# Pet Food Recall Risk Classifier")
    gr.Markdown(
        "Enter the brand name, product description, and recall reason below "
        "to predict the associated risk label(s)."
    )
    gr.Markdown(f"---\n{DISCLAIMER}")

    with gr.Row():
        brand_input = gr.Textbox(label="Brand name(s)", placeholder="e.g. Acme Pet Foods")
        product_input = gr.Textbox(
            label="Product description", placeholder="e.g. Dry dog food, 5 lb bag"
        )

    reason_input = gr.Textbox(
        label="Recall reason",
        placeholder="e.g. May contain elevated levels of Vitamin D",
        lines=3,
    )

    submit_btn = gr.Button("Classify")
    output_box = gr.Textbox(label="Predicted risk labels", interactive=False)

    submit_btn.click(
        fn=classify,
        inputs=[brand_input, product_input, reason_input],
        outputs=output_box,
    )

if __name__ == "__main__":
    demo.launch()
