"""
Gradio demo — Pet Food Recall Risk Classifier

Loads a trained multi-label text classifier from the companion Hugging Face
model repository and applies a frozen sentence-transformer encoder at inference
time.  Accepts brand name, product description, and recall reason as input;
returns predicted risk categories with confidence scores.
"""

import json

import gradio as gr
import joblib
import numpy as np
from huggingface_hub import hf_hub_download
from sentence_transformers import SentenceTransformer

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

HF_REPO = "ShurongSR/pet-food-recall-risk-classifier"
ENCODER_NAME = "sentence-transformers/all-MiniLM-L6-v2"

LABEL_EXPLANATIONS = {
    "PATHOGEN_CONTAMINATION": (
        "Bacterial or pathogen-related contamination, such as Salmonella, "
        "Listeria, or E. coli, detected in or associated with the product."
    ),
    "CHEMICAL_OR_NUTRITIONAL_RISK": (
        "Chemical, mycotoxin, heavy metal, feed additive, or vitamin/mineral "
        "imbalance risks that may affect animal health."
    ),
    "PHYSICAL_OR_QUALITY_ISSUE": (
        "Foreign material presence, packaging defects, labeling errors, "
        "import or inspection failures, or process-control issues."
    ),
}

DISCLAIMER = (
    "This tool is for educational purposes only. "
    "Predictions are generated by a machine learning model trained on a small "
    "academic dataset and may be incorrect. "
    "Always consult official FDA recall notices and a qualified veterinarian "
    "for authoritative pet food safety information."
)

# ---------------------------------------------------------------------------
# CSS
# ---------------------------------------------------------------------------

CUSTOM_CSS = """
body, .gradio-container {
    background-color: #FAF9F6 !important;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
                 "Helvetica Neue", Arial, sans-serif !important;
}

.section-heading {
    font-size: 0.75rem;
    font-weight: 700;
    color: #718096;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    margin: 0 0 0.65rem 0;
    padding: 0;
}

.label-badge {
    display: inline-block;
    background: #EBF4FF;
    color: #2B6CB0;
    border-radius: 5px;
    padding: 0.28rem 0.7rem;
    font-size: 0.82rem;
    font-weight: 600;
    margin-right: 0.4rem;
    margin-bottom: 0.4rem;
    letter-spacing: 0.02em;
}

.label-badge.low-confidence {
    background: #FFFBEB;
    color: #92400E;
    border: 1px solid #FCD34D;
}

.low-conf-warning {
    background: #FFFBEB;
    border: 1px solid #FDE68A;
    border-radius: 6px;
    padding: 0.55rem 0.85rem;
    font-size: 0.84rem;
    color: #92400E;
    margin-bottom: 0.85rem;
    line-height: 1.55;
}

.expl-row {
    font-size: 0.875rem;
    color: #4A5568;
    margin-bottom: 0.5rem;
    line-height: 1.6;
}

.score-row {
    display: flex;
    align-items: center;
    margin-bottom: 0.65rem;
    gap: 0.5rem;
}

.score-label {
    width: 290px;
    min-width: 160px;
    font-size: 0.8rem;
    color: #2D3748;
    font-weight: 500;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

.score-bar-wrap {
    flex: 1;
    background: #EDF2F7;
    border-radius: 4px;
    height: 7px;
    overflow: hidden;
}

.score-bar {
    height: 100%;
    border-radius: 4px;
    max-width: 100%;
}

.score-value {
    width: 42px;
    text-align: right;
    font-size: 0.8rem;
    color: #4A5568;
    font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace;
}

.threshold-note {
    font-size: 0.77rem;
    color: #A0AEC0;
    width: 46px;
    font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace;
}

.input-text-box {
    background: #F7FAFC;
    border: 1px solid #E2E8F0;
    border-radius: 6px;
    padding: 0.6rem 0.85rem;
    font-size: 0.82rem;
    color: #4A5568;
    font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace;
    line-height: 1.55;
    word-break: break-word;
}

.results-placeholder {
    color: #A0AEC0;
    font-size: 0.9rem;
    padding: 0.4rem 0;
    margin: 0;
}
"""

# ---------------------------------------------------------------------------
# Artifact loading (once at startup)
# ---------------------------------------------------------------------------

def _load_artifacts():
    clf_path    = hf_hub_download(repo_id=HF_REPO, filename="classifier.joblib")
    thresh_path = hf_hub_download(repo_id=HF_REPO, filename="thresholds.json")
    labels_path = hf_hub_download(repo_id=HF_REPO, filename="label_columns.json")

    clf = joblib.load(clf_path)

    with open(thresh_path, encoding="utf-8") as fh:
        thresholds = json.load(fh)["thresholds"]

    with open(labels_path, encoding="utf-8") as fh:
        label_columns = json.load(fh)

    encoder = SentenceTransformer(ENCODER_NAME)
    return clf, thresholds, label_columns, encoder


_CLF, _THRESHOLDS, _LABELS, _ENCODER = _load_artifacts()

# ---------------------------------------------------------------------------
# Prediction
# ---------------------------------------------------------------------------

def _predict(brand: str, product: str, reason: str) -> dict:
    text = f"Brand: {brand}. Product: {product}. Recall reason: {reason}."
    embedding = _ENCODER.encode([text])
    proba = _CLF.predict_proba(embedding)[0]

    predicted_labels = []
    scores = {}
    for i, label in enumerate(_LABELS):
        score = float(proba[i])
        scores[label] = round(score, 4)
        if score >= _THRESHOLDS[label]:
            predicted_labels.append(label)

    low_confidence = False
    if not predicted_labels:
        top_idx = int(np.argmax(proba))
        predicted_labels = [_LABELS[top_idx]]
        low_confidence = True

    return {
        "input_text": text,
        "predicted_labels": predicted_labels,
        "scores": scores,
        "thresholds": {lbl: _THRESHOLDS[lbl] for lbl in _LABELS},
        "low_confidence": low_confidence,
    }

# ---------------------------------------------------------------------------
# HTML renderer
# ---------------------------------------------------------------------------

def _render_results(result: dict) -> str:
    predicted  = result["predicted_labels"]
    scores     = result["scores"]
    thresholds = result["thresholds"]
    low_conf   = result["low_confidence"]
    raw_text   = result["input_text"]
    input_text = raw_text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    parts = []

    # Predicted labels
    parts.append('<p class="section-heading">Predicted Risk Categories</p>')

    if low_conf:
        parts.append(
            '<div class="low-conf-warning">'
            "No label reached its confidence threshold. "
            "The top-scoring label is shown as a low-confidence estimate."
            "</div>"
        )

    badge_cls = "label-badge low-confidence" if low_conf else "label-badge"
    badge_html = "".join(
        f'<span class="{badge_cls}">{lbl}</span>' for lbl in predicted
    )
    parts.append(f'<div style="margin-bottom:1.1rem">{badge_html}</div>')

    for lbl in predicted:
        expl = LABEL_EXPLANATIONS.get(lbl, "")
        if expl:
            parts.append(
                f'<div class="expl-row"><strong>{lbl}:</strong> {expl}</div>'
            )

    parts.append('<div style="height:1.4rem"></div>')

    # Confidence scores
    parts.append('<p class="section-heading">Confidence Scores</p>')
    for lbl in _LABELS:
        score   = scores[lbl]
        thr     = thresholds[lbl]
        is_pred = lbl in predicted
        color   = "#2B6CB0" if is_pred else "#A0AEC0"
        pct     = min(score * 100, 100)
        parts.append(
            f'<div class="score-row">'
            f'<div class="score-label">{lbl}</div>'
            f'<div class="score-bar-wrap">'
            f'<div class="score-bar" style="width:{pct:.1f}%;background:{color}"></div>'
            f"</div>"
            f'<div class="score-value">{score:.3f}</div>'
            f'<div class="threshold-note">/ {thr}</div>'
            f"</div>"
        )

    parts.append('<div style="height:1.4rem"></div>')

    # Input text used
    parts.append('<p class="section-heading">Input Text Used by Model</p>')
    parts.append(f'<div class="input-text-box">{input_text}</div>')

    return "\n".join(parts)

# ---------------------------------------------------------------------------
# Gradio callback
# ---------------------------------------------------------------------------

def classify(brand: str, product: str, reason: str) -> str:
    brand   = (brand   or "").strip()
    product = (product or "").strip()
    reason  = (reason  or "").strip()

    if not brand and not product and not reason:
        return '<p class="results-placeholder">Enter the fields above and click Classify.</p>'

    result = _predict(
        brand   or "(not provided)",
        product or "(not provided)",
        reason  or "(not provided)",
    )
    return _render_results(result)

# ---------------------------------------------------------------------------
# Interface
# ---------------------------------------------------------------------------

EXAMPLES = [
    [
        "Example Brand",
        "Dry dog food, 20 lb bag",
        "May be contaminated with Salmonella.",
    ],
    [
        "PetNutri",
        "Cat supplement, canned",
        "Contains elevated levels of Vitamin D which may be toxic to pets.",
    ],
    [
        "FreshPaws",
        "Premium cat treats, 6 oz pouch",
        "May contain small pieces of blue plastic foreign material.",
    ],
]

with gr.Blocks(title="Pet Food Recall Risk Classifier", css=CUSTOM_CSS) as demo:

    gr.HTML(
        """
        <div style="margin-bottom:1.25rem">
            <h1 style="font-size:1.55rem;font-weight:700;color:#1A202C;
                       margin:0 0 0.3rem 0;line-height:1.3;
                       font-family:inherit">
                Pet Food Recall Risk Classifier
            </h1>
            <p style="font-size:0.92rem;color:#4A5568;line-height:1.65;
                      margin:0;font-family:inherit">
                Enter a brand name, product description, and recall reason to
                predict the associated risk category. The model assigns one or
                more labels from a three-class taxonomy: pathogen contamination,
                chemical or nutritional risk, and physical or quality issue.
            </p>
        </div>
        """
    )

    with gr.Group():
        with gr.Row():
            brand_input = gr.Textbox(
                label="Brand name",
                placeholder="e.g. Acme Pet Foods",
            )
            product_input = gr.Textbox(
                label="Product description",
                placeholder="e.g. Dry dog food, 5 lb bag",
            )
        reason_input = gr.Textbox(
            label="Recall reason / safety-alert description",
            placeholder="e.g. May be contaminated with Salmonella.",
            lines=3,
        )
        classify_btn = gr.Button("Classify", variant="primary")

    output_html = gr.HTML(
        value='<p class="results-placeholder">Enter the fields above and click Classify.</p>',
    )

    gr.Examples(
        examples=EXAMPLES,
        inputs=[brand_input, product_input, reason_input],
        label="Examples",
    )

    gr.HTML(
        f"""
        <div style="border-top:1px solid #E2E8F0;margin-top:0.5rem;
                    padding-top:0.85rem">
            <p style="font-size:0.8rem;color:#718096;line-height:1.6;
                      margin:0;font-family:inherit">
                <strong>Disclaimer:</strong> {DISCLAIMER}
            </p>
        </div>
        """
    )

    classify_btn.click(
        fn=classify,
        inputs=[brand_input, product_input, reason_input],
        outputs=output_html,
    )


if __name__ == "__main__":
    demo.launch(ssr_mode=False)
